// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu7o0UuYQ1sutadmzjE7I58QYNeRueroA',
    appId: '1:161756217795:web:925d44e6123fc65e41bd76',
    messagingSenderId: '161756217795',
    projectId: 'quotemytrade-c6692',
    authDomain: 'quotemytrade-c6692.firebaseapp.com',
    storageBucket: 'quotemytrade-c6692.firebasestorage.app',
    measurementId: 'G-ZCT5W8TFLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC94sXDNS9q6dXxWGoJjW8GgvNVRJ4ZO3w',
    appId: '1:161756217795:android:ec486299e5e8436841bd76',
    messagingSenderId: '161756217795',
    projectId: 'quotemytrade-c6692',
    storageBucket: 'quotemytrade-c6692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvS2tFYNMA0sKnQ26qp5LQAgCB7nj2_go',
    appId: '1:161756217795:ios:835bd606c7b4944341bd76',
    messagingSenderId: '161756217795',
    projectId: 'quotemytrade-c6692',
    storageBucket: 'quotemytrade-c6692.firebasestorage.app',
    iosClientId: '161756217795-u3c1jgfbas7s9u85an80fe1lolik5l20.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotemytrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvS2tFYNMA0sKnQ26qp5LQAgCB7nj2_go',
    appId: '1:161756217795:ios:835bd606c7b4944341bd76',
    messagingSenderId: '161756217795',
    projectId: 'quotemytrade-c6692',
    storageBucket: 'quotemytrade-c6692.firebasestorage.app',
    iosClientId: '161756217795-u3c1jgfbas7s9u85an80fe1lolik5l20.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotemytrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu7o0UuYQ1sutadmzjE7I58QYNeRueroA',
    appId: '1:161756217795:web:c1c7c9f61b2e1c8241bd76',
    messagingSenderId: '161756217795',
    projectId: 'quotemytrade-c6692',
    authDomain: 'quotemytrade-c6692.firebaseapp.com',
    storageBucket: 'quotemytrade-c6692.firebasestorage.app',
    measurementId: 'G-RMCN4P12QE',
  );
}
